# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import os
import pathlib
import typing
from . import slurm

__all__ = [
    "CalcType",
    "JobFlow",
    "slurm",
]

@typing.final
class CalcType:
    @property
    def value(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, value: builtins.str) -> CalcType: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class JobFlow:
    @property
    def uuid(self) -> builtins.str: ...
    @uuid.setter
    def uuid(self, value: builtins.str) -> None: ...
    @property
    def calc_type(self) -> CalcType: ...
    @calc_type.setter
    def calc_type(self, value: CalcType) -> None: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    @created_at.setter
    def created_at(self, value: datetime.datetime) -> None: ...
    @property
    def work_dir(self) -> pathlib.Path: ...
    @work_dir.setter
    def work_dir(self, value: builtins.str | os.PathLike | pathlib.Path) -> None: ...
    @property
    def tags(self) -> builtins.dict[builtins.str, builtins.str]: ...
    @tags.setter
    def tags(self, value: typing.Mapping[builtins.str, builtins.str]) -> None: ...
    @property
    def jobs(self) -> builtins.dict[builtins.str, slurm.Job]:
        r"""
        Returns the jobs map keyed by `JobId.value` (str). To mutate, build a
        fresh dict and re-assign — list/dict mutation on the returned dict
        does not write back to the underlying Rust value.
        """
    @jobs.setter
    def jobs(self, value: typing.Mapping[builtins.str, slurm.Job]) -> None: ...
    def __new__(
        cls,
        uuid: builtins.str,
        calc_type: CalcType,
        created_at: datetime.datetime,
        work_dir: builtins.str | os.PathLike | pathlib.Path,
        tags: typing.Mapping[builtins.str, builtins.str] = {},
        jobs: typing.Mapping[builtins.str, slurm.Job] = {},
    ) -> JobFlow:
        r"""
        Build a `JobFlow`. `uuid` accepts the canonical hyphenated string form
        (e.g. `"01997cdc-…"`). To generate a fresh UUID v7, call
        `JobFlow.new_uuid()`.
        """
    @staticmethod
    def new_uuid() -> builtins.str:
        r"""
        Generate a fresh UUID v7 helper to feed into `JobFlow(...)`.
        """
    def insert_job(self, id: slurm.JobId, job: slurm.Job) -> None:
        r"""
        Convenience: insert a single job under the given `JobId`.
        """
    def get_job(self, id: slurm.JobId) -> typing.Optional[slurm.Job]:
        r"""
        Convenience: get a job by id (returns `None` if missing).
        """
    def __repr__(self) -> builtins.str: ...
