# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import slurm_async_runner._slurm_async_runner_core.entities.slurm.sbatch_options
import typing

__all__ = [
    "CalcType",
    "Job",
    "JobEdge",
    "JobFlow",
    "JobId",
    "JobSpec",
    "Program",
]

@typing.final
class CalcType:
    @property
    def value(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, value: builtins.str) -> CalcType: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class Job:
    @property
    def spec(self) -> JobSpec: ...
    @spec.setter
    def spec(self, value: JobSpec) -> None: ...
    @property
    def parents(self) -> builtins.list[JobEdge]:
        r"""
        Returns a *copy* of the parent edges. To mutate, re-assign the
        whole list: `job.parents = job.parents + [edge]`.
        """
    @parents.setter
    def parents(self, value: typing.Sequence[JobEdge]) -> None: ...
    def __new__(cls, spec: JobSpec, parents: typing.Sequence[JobEdge] = []) -> Job: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class JobEdge:
    @property
    def from_(self) -> JobId: ...
    @from_.setter
    def from_(self, value: JobId) -> None: ...
    @property
    def kind(self) -> typing.Any:
        r"""
        Returns SAR's canonical `DependencyType` Python enum value
        (looked up at runtime via `Py::import` to satisfy the Pyclass
        Single Owner rule — shared2 never owns a `DependencyType` pyclass).
        """
    @kind.setter
    def kind(
        self,
        value: sbatch_options.slurm_async_runner._slurm_async_runner_core.entities.slurm.sbatch_options.DependencyType,
    ) -> None: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __new__(
        cls,
        from_: JobId,
        kind: sbatch_options.slurm_async_runner._slurm_async_runner_core.entities.slurm.sbatch_options.DependencyType,
    ) -> JobEdge:
        r"""
        `from_` is spelled with a trailing underscore on the Python side
        because `from` is a reserved word.

        `kind` accepts SAR's `DependencyType` Python enum (duck-typed via
        `DependencyTypeBridge`). At runtime any object whose `str(...)` is
        a recognised Slurm dependency keyword is accepted.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class JobFlow:
    @property
    def uuid(self) -> builtins.str: ...
    @uuid.setter
    def uuid(self, value: builtins.str) -> None: ...
    @property
    def created_at(self) -> datetime.datetime: ...
    @created_at.setter
    def created_at(self, value: datetime.datetime) -> None: ...
    @property
    def tags(self) -> builtins.dict[builtins.str, builtins.str]: ...
    @tags.setter
    def tags(self, value: typing.Mapping[builtins.str, builtins.str]) -> None: ...
    @property
    def jobs(self) -> builtins.dict[builtins.str, Job]:
        r"""
        Returns the jobs map keyed by `JobId.value` (str). To mutate, build a
        fresh dict and re-assign — list/dict mutation on the returned dict
        does not write back to the underlying Rust value.
        """
    @jobs.setter
    def jobs(self, value: typing.Mapping[builtins.str, Job]) -> None: ...
    def __new__(
        cls,
        uuid: builtins.str,
        created_at: datetime.datetime,
        tags: typing.Mapping[builtins.str, builtins.str] = {},
        jobs: typing.Mapping[builtins.str, Job] = {},
    ) -> JobFlow:
        r"""
        Build a `JobFlow`. `uuid` accepts the canonical hyphenated string form
        (e.g. `"01997cdc-…"`). To generate a fresh UUID v7, call
        `JobFlow.new_uuid()`.
        """
    @staticmethod
    def new_uuid() -> builtins.str:
        r"""
        Generate a fresh UUID v7 helper to feed into `JobFlow(...)`.
        """
    def insert_job(self, id: JobId, job: Job) -> None:
        r"""
        Convenience: insert a single job under the given `JobId`.
        """
    def get_job(self, id: JobId) -> typing.Optional[Job]:
        r"""
        Convenience: get a job by id (returns `None` if missing).
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class JobId:
    @property
    def value(self) -> builtins.str:
        r"""
        String value held by this `JobId`.
        """
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, value: builtins.str) -> JobId: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...

@typing.final
class JobSpec:
    @property
    def program(self) -> Program: ...
    @program.setter
    def program(self, value: Program) -> None: ...
    @property
    def config(self) -> typing.Any:
        r"""
        Get the SLURM config as a Python `SlurmJobConfig` instance.

        **Limitation:** This getter only round-trips the `partition` field.
        All other fields (`time_limit`, `resource_spec`, `log_stdout`,
        `log_stderr`, `comment`, `job_name`, `mail_user`) are dropped — the
        returned Python object will have those defaulted to SAR's `__new__`
        defaults (`None` for most). The full Rust-side state is preserved
        in `self.0.config`; the loss is only in the Python projection.

        **Beware:** self-assignment (`spec.config = spec.config`) silently
        destroys all dropped fields because the round-trip goes through this
        getter. Mutate the underlying config in-place (or build a fresh
        `SlurmJobConfig` with the desired fields) instead of read-modify-write.

        Tracked in
        <https://github.com/kkiyama117/gaussian_job_shared/issues/4>.
        The fix is to expand the `cls.call1((..., ..., ...))` arg tuple to
        include every field, once SAR's `SlurmJobConfig.__new__`
        keyword-argument signature is stable.
        """
    @config.setter
    def config(
        self,
        value: sbatch_options.slurm_async_runner._slurm_async_runner_core.entities.slurm.sbatch_options.SlurmJobConfig,
    ) -> None: ...
    @property
    def body(self) -> builtins.str: ...
    @body.setter
    def body(self, value: builtins.str) -> None: ...
    def __new__(
        cls,
        program: Program,
        config: sbatch_options.slurm_async_runner._slurm_async_runner_core.entities.slurm.sbatch_options.SlurmJobConfig,
        body: builtins.str,
    ) -> JobSpec:
        r"""
        `config` accepts SAR's `SlurmJobConfig` Python class (duck-typed
        via `SlurmJobConfigBridge`). At runtime any object exposing the
        expected attributes is accepted.
        """
    def __repr__(self) -> builtins.str: ...

@typing.final
class Program:
    @property
    def value(self) -> builtins.str: ...
    def __eq__(self, other: builtins.object, /) -> builtins.bool: ...
    def __lt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __le__(self, other: builtins.object, /) -> builtins.bool: ...
    def __gt__(self, other: builtins.object, /) -> builtins.bool: ...
    def __ge__(self, other: builtins.object, /) -> builtins.bool: ...
    def __hash__(self) -> builtins.int: ...
    def __new__(cls, value: builtins.str) -> Program: ...
    def __str__(self) -> builtins.str: ...
    def __repr__(self) -> builtins.str: ...
