#[cfg(feature = "pyo3-types")]
pub mod py_export;

// The `stub_info` symbol is generated by the
// `pyo3_stub_gen::define_stub_info_gatherer!` macro inside
// `py_export::mod` under the `stub_gen` feature; surface it here only
// when stub generation is enabled.
#[cfg(feature = "stub_gen")]
pub use py_export::stub_info;

/// config that are defined in config file
pub mod config;

/// (frozen) Entities of config, data, and so on.
pub mod entities;

/// Errors raise from this library.
pub mod error;
